apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: balu361988/small:17  # Image name and tag
          ports:
            - containerPort: 3000  # Port your app listens on

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 3000  # Port your container listens on
  type: ClusterIP  # You can change this to LoadBalancer or NodePort if you want external access
